### ISSUE TITLE
Buffer overload problems with adm-zip

### ISSUE THREAD

**Issue by tinganho** [rxaviers/cldr-data-downloader#14]
Hi @rxaviers 

I've had some problem downloading and unzipping CLDR for low-memory hardware.
The issue is related to `asm-zip`: https://github.com/cthackers/adm-zip/issues/129.

Maybe @focusaurus can give you more details. I don't have access to low-memory hardware.

**Comment by focusaurus** [comment]
The details aren't very exciting. Take a multi-megabyte compress zip file and try to load the entire uncompressed buffer into RAM on an EC2 small instance that's already running a bunch of services. On linux, the OOM killer just kills the process Game of Thrones style

**Comment by focusaurus** [comment]
Here's the output. The "Killed" is the OOM killer.

    GET `http://www.unicode.org/Public/cldr/26.0.1/json-full.zip`
      [========================================] 100% 0.0s
    Received 52540K total.
    Unpacking it into `./`
    Killed

**Comment by focusaurus** [comment]
My suggestion would be to switch to a memory-efficient zip extraction module. I don't think adm-zip is going to get a timely fix and I'm confident there is a high-quality alternative in the npm registry somewhere.

**Comment by rxaviers** [comment]
52MB is indeed very large package. What about CLDR 27? If you can upgrade for using CLDR 27, it has changed how data is distributed. It's now using a dozen of packages that could be enqueued on decompression. Please, could you give it a try and let me know?

**Comment by tinganho** [comment]
I haven't yet switched to CLDR 27. I would do it ASAP.

@rxaviers are there any relevant info about `en-US` language tag not being in `main/`? Because that is currently breaking my test suit.

**Comment by rxaviers** [comment]
> Default content locales - In order to keep the data size to a minimum, JSON data for default content locales will not be included in the installable packages.  Since all default content locales can retrieve their data from the parent via simple inheritance ( i.e. removal of the rightmost portion of the language tag ), this should be relatively easy for most JavaScript applications to determine the appropriate location from which to retrieve the data.  A new JSON file "defaultContent.json" shall be included in CLDR's as part of the cldr-core package, in the top level directory,  that will contain the list of default content locales for the release.

http://cldr.unicode.org/development/development-process/design-proposals/json-packaging

In summary, `en-US` is not there. Because, it's the default for `en` (which is present).

**Comment by rxaviers** [comment]
Also note that CLDR 27.0.1 has a minor fix that includes `defaultContent.json` as stated below.

> The approved JSON packaging document stated that the cldr-core package would contain "defaultContent.json", which would list the locale identifiers that were omitted from the JSON packaging because they were identical to the parent. This file was inadvertently omitted from the v27 distribution. See [#8302]

http://cldr.unicode.org/index/downloads/cldr-27#27-0-1

**Comment by tinganho** [comment]
@rxaviers I think `cldr-data` is just downloading `27.0.0`. I can't find the `defaultContent.json` file:

```
GET `https://github.com/unicode-cldr/cldr-core/archive/27.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-segments-modern/archive/27.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-dates-full/archive/27.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-buddhist-full/archive/27.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-chinese-full/archive/27.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-coptic-full/archive/27.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-dangi-full/archive/27.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-ethiopic-full/archive/27.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-hebrew-full/archive/27.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-indian-full/archive/27.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-islamic-full/archive/27.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-japanese-full/archive/27.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-persian-full/archive/27.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-cal-roc-full/archive/27.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-localenames-full/archive/27.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-misc-full/archive/27.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-numbers-full/archive/27.0.0.zip`
GET `https://github.com/unicode-cldr/cldr-units-full/archive/27.0.0.zip`
  [========================================] 103585/0 100% 0.0s
Received 38992K total.
Unpacking it into `./`
cldr-data@27.0.1 node_modules/cldr-data
└── cldr-data-downloader@0.2.2 (progress@1.1.8, adm-zip@0.4.4, nopt@3.0.1, request-progress@0.3.1, npmconf@2.0.9)
```

**Comment by rxaviers** [comment]
I've just updated `cldr-data@27.x` to fetch `27.0.1`. Although, I still don't see this file. It should be present on https://github.com/unicode-cldr/cldr-core/ according to http://cldr.unicode.org/development/development-process/design-proposals/json-packaging and http://unicode.org/cldr/trac/ticket/8302

**Comment by tinganho** [comment]
@rxaviers `defaultContent.json` is on https://github.com/unicode-cldr/cldr-core/ now. But I don't think I can find it on `cldr-data`?

**Comment by rxaviers** [comment]
@JCEmmons, hi! Are you going to tag it (create a new patch release) so we can use `defaultContent.json` inclusion?

**Comment by tinganho** [comment]
ping @JCEmmons

**Comment by JCEmmons** [comment]
I hadn't planned on tagging a new release, but I suppose I can if it would make things easier ( since it was due to an error on my part )......

**Comment by rxaviers** [comment]
If tagging is not a problem, yeap it would help. Thanks

On Tuesday, April 21, 2015, John Emmons <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

> I hadn't planned on tagging a new release, but I suppose I can if it would
> make things easier ( since it was due to an error on my part )......
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rxaviers/cldr-data-downloader/issues/14#issuecomment-94834736>
> .
>


-- 
+55 (16) 98138-1583, +1 (415) 568-5854, skype: rxaviers
http://rafael.xavier.blog.br

**Comment by JCEmmons** [comment]
All CLDR packages are now tagged as 27.0.3 as latest, which includes 
defaultContent.json.


Regards,

John C. Emmons
Globalization Architect & Unicode CLDR TC Chairman
IBM Software Group
Internet: emmo@us.ibm.com

**Comment by rxaviers** [comment]
Awesome, thank you!

rxaviers/cldr-data-npm has been updated as well (https://github.com/rxaviers/cldr-data-npm/commit/8bc15a83cc6f2dd41795d1fed5dca9448a03989d).

**Comment by rxaviers** [comment]
@tinganho, @focusaurus, does it solve your problem?

**Comment by tinganho** [comment]
@focusaurus I have now updated `l10ns@v2.2` to use the new `cldr-data-npm`. Do you mind give it a try?

**Comment by focusaurus** [comment]
With these changes, I am able to successfully install l10ns on the server that was unable to do so before. Thanks!

    npm install l10ns@latest
    \
    > cldr-data@27.0.3 install /tmp/node_modules/l10ns/node_modules/cldr-data
    > node install.js

    GET `https://github.com/unicode-cldr/cldr-core/archive/27.0.3.zip`
    GET `https://github.com/unicode-cldr/cldr-segments-modern/archive/27.0.3.zip`
    GET `https://github.com/unicode-cldr/cldr-dates-full/archive/27.0.3.zip`
    GET `https://github.com/unicode-cldr/cldr-cal-buddhist-full/archive/27.0.3.zip`
    GET `https://github.com/unicode-cldr/cldr-cal-chinese-full/archive/27.0.3.zip`
    GET `https://github.com/unicode-cldr/cldr-cal-coptic-full/archive/27.0.3.zip`
    GET `https://github.com/unicode-cldr/cldr-cal-dangi-full/archive/27.0.3.zip`
    GET `https://github.com/unicode-cldr/cldr-cal-ethiopic-full/archive/27.0.3.zip`
    GET `https://github.com/unicode-cldr/cldr-cal-hebrew-full/archive/27.0.3.zip`
    GET `https://github.com/unicode-cldr/cldr-cal-indian-full/archive/27.0.3.zip`
    GET `https://github.com/unicode-cldr/cldr-cal-islamic-full/archive/27.0.3.zip`
    GET `https://github.com/unicode-cldr/cldr-cal-japanese-full/archive/27.0.3.zip`
    GET `https://github.com/unicode-cldr/cldr-cal-persian-full/archive/27.0.3.zip`
    GET `https://github.com/unicode-cldr/cldr-cal-roc-full/archive/27.0.3.zip`
    GET `https://github.com/unicode-cldr/cldr-localenames-full/archive/27.0.3.zip`
    GET `https://github.com/unicode-cldr/cldr-misc-full/archive/27.0.3.zip`
    GET `https://github.com/unicode-cldr/cldr-numbers-full/archive/27.0.3.zip`
    GET `https://github.com/unicode-cldr/cldr-units-full/archive/27.0.3.zip`
      [========================================] 27620272/128462 100% 0.0s
    Received 39062K total.
    Unpacking it into `./`
    l10ns@2.2.0 ../node_modules/l10ns

**Comment by rxaviers** [comment]
Awesome!

**Comment by tinganho** [comment]
:+1:
