### ISSUE TITLE
Support filesystem location of the cldr files

### ISSUE THREAD

**Issue by alex-stripe** [rxaviers/cldr-data-downloader#25]
In order to reduce dependencies on external services in our builds, I have a need to just pass a file system path to the relevant zip files.

e.g.

```json
{
  "core": [
    "file://path/to/cldrstuff/cldr-core/archive/31.0.1.zip",
    "file://path/to/cldrstuff/cldr-dates-modern/archive/31.0.1.zip",
    "file://path/to/cldrstuff/cldr-cal-buddhist-modern/archive/31.0.1.zip",
    "file://path/to/cldrstuff/cldr-cal-chinese-modern/archive/31.0.1.zip",
    "file://path/to/cldrstuff/cldr-cal-coptic-modern/archive/31.0.1.zip"
  ]
}
```

AND/OR

```json
{
  "core": [
    "../../cldr-core/archive/31.0.1.zip",
    "../../cldr-dates-modern/archive/31.0.1.zip",
    "../../cldr-cal-buddhist-modern/archive/31.0.1.zip",
    "../../cldr-cal-chinese-modern/archive/31.0.1.zip",
    "../../cldr-cal-coptic-modern/archive/31.0.1.zip"
  ]
}
```

Since the paths get passed directly into `request` they fail, because it doesn't support file paths. I can get files in S3, but can only retrieve them over the `s3://` protocol, which seems far-fetched to support here. I can set up a little server that serves them from the file system to work around it, but that doesn't feel great :D.

I'm happy to submit a PR for this if you're interested in supporting it.

**Comment by rxaviers** [comment]
Hi @alex-stripe!

I'm certainly happy to support a `file` protocol.

**Comment by alex-stripe** [comment]
Cool. I'll send a PR shortly (hopefully).

**Comment by rxaviers** [comment]
Awesome

**Comment by SlexAxton** [comment]
Sorry was on my work account :D but I'll do the PR from this one. <3z

**Comment by rxaviers** [comment]
:)

**Comment by rxaviers** [comment]
It would be great to get your feedback about a related topic: cache downloads? https://github.com/rxaviers/cldr-data-npm/issues/28

**Comment by SlexAxton** [comment]
commented there.
