### ISSUE TITLE
Release changes to npm

### ISSUE THREAD

**Issue by dantman** [rxaviers/cldr-data-downloader#32]
It would be nice if a new version were released to NPM.

Six months ago [npmconf was removed](https://github.com/rxaviers/cldr-data-downloader/commit/83c3e08908ec68eb0a5b91b29fd5ee4da24cc2cb) from this package, but this change has not been released to npm.

The version in npm still uses npmconf, which is a bit annoying because this package was depending on an obsolete version of the package that has an invalid `license` property. Which can trip up simple licence checking code.

**Comment by rxaviers** [comment]
0.3.3 just released. Thanks for pushing and sorry for the delay.
