### ISSUE TITLE
Security vulnerability due to request version

### ISSUE THREAD

**Issue by briangleeson** [rxaviers/cldr-data-downloader#35]
λ nsp check
(+) 1 vulnerability found

|      | Prototype pollution attack |
| ---------- |:-------------:|
| Name | hoek |
| CVSS | 4 (Medium) |
| Installed  | 2.16.3 |
| Vulnerable | <= 4.2.0 || >= 5.0.0 < 5.0.3 |
| Patched | > 4.2.0 < 5.0.0 || >= 5.0.3 |
| Path | ess-appregistry-client@0.1.0 > cldr-data@32.0.1 > |
|            | cldr-data-downloader@0.3.3 > request@2.81.0 > hawk@3.1.3 >|
|            | hoek@2.16.3 |
| More Info  | https://nodesecurity.io/advisories/566 |

I believe this can be fixed by upgrading to use request 2.83,  but I don't know if that would have any impact on functionality

See here: https://github.com/request/request/issues/2874

**Comment by rxaviers** [comment]
Thanks for reporting this. Please would you like to submit a PR bumping the package up?

**Comment by briangleeson** [comment]
I certainly can, but I don't know how one would test it out to ensure that nothing is broken

**Comment by briangleeson** [comment]
Unfortunately this didnt quite do the trick. New error:

|      | Prototype pollution attack |
| ---------- |:-------------:|
| Name | hoek |
| CVSS | 4 (Medium) |
| Installed  | 2.16.3 |
| Vulnerable | <= 4.2.0 || >= 5.0.0 < 5.0.3 |
| Patched | > 4.2.0 < 5.0.0 || >= 5.0.3 |
| Path | ess-appregistry-client@0.1.0 > cldr-data@32.0.1 >  |
|            | cldr-data-downloader@0.3.4 > request@2.83.0 > hawk@6.0.2 > |
|            | cryptiles@3.1.2 > boom@5.2.0 > hoek@2.16.3  |
| More Info  | https://nodesecurity.io/advisories/566 |

**Comment by rxaviers** [comment]
Do you need to patch `request`?

**Comment by briangleeson** [comment]
Actually scratch that, the new error was down to a package lock file in our pipeline. Sorted that out and got a clean security scan this time around

**Comment by rxaviers** [comment]
Excellent!

**Comment by rxaviers** [comment]
Fixed by #36
