### ISSUE TITLE
Incompatible GPL-licensed code

### ISSUE THREAD

**Issue by achrinza** [rxaviers/cldr-data-downloader#40]
# Issue
`cldr-data-downloader` has the direct dependency, `adm-zip@0.4.11`, that is licensed under MIT. However, it also [contains code that is licensed under `GPL-2.0-only`](https://github.com/cthackers/adm-zip/issues/77).

This is incompatible with the `MIT` license of this project and is also problematic with `Apache-2.0`.

This has been fixed in `adm-zip@0.4.13`.

## [FOSSA](https://fossa.com/) Snippet

![image](https://user-images.githubusercontent.com/25147899/68183857-799f1b80-ffd8-11e9-9199-c5493a5a0cca.png)

# Fix
Update dependency to `adm-zip@0.4.13`.

**Comment by rxaviers** [comment]
Sure, I am open to merge a PR with such change

**Comment by achrinza** [comment]
The PR has been created

**Comment by achrinza** [comment]
@rxaviers Just checking in, when would the changes be published?
