### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by RelentlessResults** [rxaviers/cldr-data-downloader#45]
https://github.com/rxaviers/cldr-data-downloader/blob/2ad2712d73e24db3da9a5ee57b4ad376e2102bb7/package.json#L39
Please bump to mkdirp@1.0.0 since 0.5.0 depends on minimist@0.0.8 which has a Prototype Pollution security issue:
https://www.npmjs.com/advisories/1179

**Comment by oosterholt** [comment]
Pull request is already created #44

**Comment by cmawhorter** [comment]
FWIW -- minimist now has critical level vulns: https://github.com/advisories/GHSA-xvch-5gv4-984h
