### ISSUE TITLE
Should include a default src URL

### ISSUE THREAD

**Issue by eemeli** [rxaviers/cldr-data-downloader#5]
If the module is called with no `srcUrl`, the `assert()` [here](/rxaviers/cldr-data-downloader/blob/master/index.js#L32) fails. Shouldn't cldr-data-downloader instead default to the latest official release? It's available here: http://www.unicode.org/Public/cldr/latest/json.zip

**Comment by Mottie** [comment]
It appears that the json.zip file (http://www.unicode.org/Public/cldr/latest/json.zip) no longer exists.

**Comment by rxaviers** [comment]
Closing for now due to low traction. We could re-open if there's interest.
