### ISSUE TITLE
Release a new version with updated mkdirp

### ISSUE THREAD

**Issue by compulim** [rxaviers/cldr-data-downloader#50]
Although PR #44 is merged, a new release has not been published yet.

![image](https://user-images.githubusercontent.com/1622400/126315921-dcadd1db-4a45-449a-adc8-d34a57ba5e7b.png)

Could we do a new release sooner?

**Comment by batmanwannabe** [comment]
This would fix the security vulnerability :  https://www.npmjs.com/advisories/1179

**Comment by steven-coding** [comment]
I would like to have this, too. 👍 
Let's get rid of that security issue.

Thanks in advance!

**Comment by rxaviers** [comment]
Fixed by 3588eb9
